[config]
skip_core_tasks = true

###################
## Manual Deploy ##
###################

[tasks.build-and-deploy]
run_task = [{name = [
    "build-production",
    "deploy-local",
]}]

[tasks.deploy-local]
script = ["firebase deploy --project ji-kids --only hosting:ji-kids-red-sea-race"]

##################
## Main Entries ##
##################

[tasks.build]
run_task = [
    {name = "build-development", condition = { profiles = [ "development"] } },
    {name = "build-production", condition = { profiles = [ "production"] } },
]

[tasks.watch]
command = "watchexec"
args = ["-w", "./src", "-w", "../../dakom/shipyard-scenegraph/crate/src", "makers", "build-development"]

[tasks.watch-quiet]
command = "watchexec"
args = ["-w", "./src", "-w", "../../dakom/shipyard-scenegraph/crate/src", "makers", "build-development-quiet"]

[tasks.clean]
script_runner = "@shell"
ignore_errors = true
script = [ 
    "rm -rf ./target",
    "rm -rf ./pkg",
    "rm -rf ./_static/wasm/app",
	"rm -rf ./dist"
]

#################
## Development ##
#################

[tasks.build-development]
run_task = [{name = [
    "compile-development", 
    "bindgen-development"
]}]

[tasks.build-development-quiet]
run_task = [{name = [
    "compile-development-quiet", 
    "bindgen-development"
]}]

[tasks.compile-development]
command = "cargo"
args = ["build","--features","dev","--target","wasm32-unknown-unknown"]
toolchain = "nightly"

[tasks.compile-development-quiet]
command = "cargo"
args = ["build","--features","dev quiet","--target","wasm32-unknown-unknown"]
toolchain = "nightly"

[tasks.bindgen-development]
command = "wasm-bindgen"
args = ["./target/wasm32-unknown-unknown/debug/app.wasm","--debug", "--keep-debug", "--target","web","--out-dir","./_static/wasm/app/pkg"]


################
## Production ##
################

[tasks.build-production]
run_task = [{name = [
	"clean-dist",
    "compile-production", 
    "bindgen-production",
    "wasmopt-production",
	"copy-static",
]}]

[tasks.compile-production]
command = "cargo"
args = ["build","--release","--target","wasm32-unknown-unknown"]
toolchain = "nightly"

[tasks.bindgen-production]
command = "wasm-bindgen"
args = ["./target/wasm32-unknown-unknown/release/app.wasm", "--target","web","--out-dir","./_static/wasm/app/pkg"]

[tasks.wasmopt-production]
command = "wasm-opt"
# if CI fails, try with BINARYEN_CORES=1 in an env
args = ["-O3","-o","./_static/wasm/app/pkg/app_bg.wasm", "./_static/wasm/app/pkg/app_bg.wasm"]

##################
## Copy Static ##
#################

[tasks.clean-dist]
script_runner = "@shell"
script = ["rm -rf ./dist/"]

[tasks.copy-static]
script_runner = "@shell"
script = ["cp -R ./_static/* ./dist/"]